server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres!

        # mustache path : sec/main/resources
        # mustache : templates (prefix), .mustache (suffix) >> config로 재설정함

    jpa:
        hibernate:
            ddl-auto: update #create update none
        show-sql: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${CLIENT_ID}
                        client-secret: ${CLIENT_SECRET}
                        scope:
                            - email
                            - profile

                    facebook:
                        client-id: ${FACEBOOK_CLIENT_ID}
                        client-secret: ${{FACEBOOK_CLIENT_SECRET}
                        scope:
                            - email
                            - public_profile

