server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres!

        #???? ?? ?? sec/main/resources
        #???? ?? : templates (prefix), .mustache (suffix) >> ??? ??? ?? ???? ????

jpa:
    hibernate:
        ddl-auto: create #create update none
        naming:
            physical-strategy:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true